repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      # - id: name-tests-test

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|rst|yml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [--fail-under=80, --verbose]
        exclude: (^tests/|^coral_ordinal/version\.py$|^coral_ordinal/tests/)

  -   repo: local
      hooks:
      -   id: pytest-check
          stages: [push]
          types: [python]
          name: pytest-check
          entry: python -m pytest -v tests/
          language: system
          pass_filenames: false
          always_run: true
